xcodeproj 'SPLRemoteObject'
workspace '../SPLRemoteObject'
inhibit_all_warnings!

platform :ios, '7.0'
link_with 'SPLRemoteObjectTests'

pod 'OCMock'
pod 'Expecta'
pod 'SPLRemoteObject', :path => '..'
